apps/registry/urls.py
from django.urls import include, path
from rest_framework import routers
from apps.registry.export.receipt import MyReceiptView
from apps.registry.views.person import PersonSearchView

from apps.registry.views.receipt import ReceiptCreateView, ReceiptDeleteView, ReceiptDetail, ReceiptSaveView, ReciptList
from apps.registry.views.service import ServiceCreateView, ServiceDeleteView, ServiceList, ServiceUpdateView

app_name = 'registry'
urlpatterns = [
    path('receipt/list', ReciptList.as_view(), name="receipt_list"),
    path('receipt/create', ReceiptCreateView.as_view(), name="receipt_create"),
    path('receipt/save', ReceiptSaveView.as_view(), name="receipt_save"),
    path('receipt/<uuid:pk>/detail', ReceiptDetail.as_view(), name="receipt_detail"),
    path('person/search', PersonSearchView.as_view(), name="person_search"),
    path('receipt/<uuid:pk>/delete', ReceiptDeleteView.as_view(), name="receipt_delete"),
    
    path('service/list', ServiceList.as_view(), name='service_list'),
    path('service/crear', ServiceCreateView.as_view(), name='service_create'),
    path('service/<uuid:pk>/update', ServiceUpdateView.as_view(), name='service_update'),
    path('service/<uuid:pk>/delete', ServiceDeleteView.as_view(), name='service_delete'),
    
    path('export/receipt/<uuid:pk>', MyReceiptView.as_view(), name='my_report'),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import TemplateView
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from apps.registry.views.dashboard import DashboardView

urlpatterns = [
    path('', TemplateView.as_view(template_name="index.html"), name='index'),
    path('admin/', admin.site.urls),
    # path('summernote/', include('django_summernote.urls')),
    path('dauth/', include('apps.dauth.urls'), name='dauth'),
    
    path('dashboard', DashboardView.as_view(), name='dashboard'),
    path('account/', include('apps.account.urls'), name='account'),
    path('registry/', include('apps.registry.urls'), name='registry'),
    
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/registry/models/detail.py
from uuid import uuid4
from django.db import models

from .receipt import Receipt
from .service import Service


class Detail(models.Model):
    """
    - registry
    - service
    - cost: from service cost
    """
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    receipt = models.ForeignKey(Receipt, related_name='details', on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    cost = models.DecimalField(max_digits=7, decimal_places=2, default=0.00)

    class Meta:
        verbose_name = "Detail"
        verbose_name_plural = "Details"

    def __str__(self):
        return "%s" % self.receipt

apps/registry/models/person.py
from statistics import mode
from uuid import uuid4
from django.db import models


class Person(models.Model):
    """
    - first_name
    - last_name
    - cedule
    - email
    - cellphone
    - address
    """
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    first_name = models.CharField("Nombres", max_length=40)
    last_name = models.CharField("Apellidos", max_length=60)
    cedule = models.CharField("DNI", max_length=10, unique=True)
    email = models.EmailField("Correo", max_length=80, blank=True, null=True)
    cellphone = models.CharField("Celular", max_length=13, blank=True, null=True)
    address = models.CharField("Dirección", max_length=200)

    class Meta:
        verbose_name = "Person"
        verbose_name_plural = "Personas"

    def __str__(self):
        return self.first_name

apps/registry/models/receipt.py
from statistics import mode
from uuid import uuid4
from django.db import models

from .person import Person


class Receipt(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    number = models.IntegerField()
    date = models.DateTimeField()
    client = models.ForeignKey(Person, related_name="receipts", on_delete=models.CASCADE)

    discount = models.DecimalField(max_digits=7, decimal_places=2, default=0.00)
    total = models.DecimalField(max_digits=7, decimal_places=2, default=0.00)
  
    created_by = models.CharField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Comprobante"
        verbose_name_plural = "Comprobantes"

    def __str__(self):
        return "%s" % self.number

apps/registry/models/service.py
from uuid import uuid4
from django.db import models


class Service(models.Model):
    """
    - code
    - description
    - cost:decimal
    - is_public:boolean
    """
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    code = models.CharField("Código", max_length=15)
    description = models.CharField("Descripción", max_length=35)
    cost = models.DecimalField("Costo", max_digits=7, decimal_places=2, default=0.00)
    is_public = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Servicio"
        verbose_name_plural = "Servicios"

    def __str__(self):
        return self.description

apps/registry/forms/service.py
from crispy_forms.bootstrap import FormActions
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Div, Field

from django import forms

from ..models.service import Service
from apps.utils.forms import smtSave, btnCancel, btnReset


class ServiceModelForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ("code", "description", "cost", 'is_public')
        widgets = {
            'code': forms.TextInput(attrs={'placeholder': 'Ingrese el código del servicio'}),
            'description': forms.TextInput(attrs={'placeholder': 'Ingrese la descripción del servicio'}),
            'cost': forms.NumberInput(attrs={'placeholder': 'Ingrese el costo', 'step':'any'}),
            'is_public': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

    def __init__(self, *args, **kwargs):
        super(ServiceModelForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
            Div(Field('code', css_class='input-required')),
            Div(Field('description')),
            Div(Field('cost')),
            Div(Field('is_public')),
            Row(
                FormActions(
                    Div(
                        smtSave(),
                        btnReset(),
                        btnCancel(),
                        css_class='btn-group')
                ),
            ),
        )

apps/registry/views/dashboard.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard.html'
    # context_object_name = 'object'

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        context['title'] = 'Dashboard'
        return context

apps/registry/views/person.py
from django.db.models import Count
from django.contrib import messages
from django.http import JsonResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView, View
from django.urls import reverse, reverse_lazy
from django.utils.text import capfirst
from django.utils.encoding import force_bytes, force_text
from ..models.person import Person


class PersonSearchView(View):
    def get(self, request, *args, **kwargs):
        cedule = request.GET.get('cedule')
        qs = Person.objects.filter(cedule=cedule).values('first_name', 'last_name','email','cellphone','address')
        if qs.exists():
            return JsonResponse({'ok':True, 'person':qs[0]})
        return JsonResponse({'ok':False})

apps/registry/views/receipt.py
import json
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.views import View
from django.views.generic import ListView, DetailView, TemplateView
from django.urls import reverse, reverse_lazy
from ..models.person import Person

from apps.utils.util import empty
from ..models.receipt import Receipt
from ..models.service import Service
from ..models.detail import Detail


class ReciptList(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = 'receipt/list.html'

    def get_paginate_by(self, queryset):
        if 'all' in self.request.GET:
            return None
        return ListView.get_paginate_by(self, queryset)

    def get_queryset(self):
        self.paginate_by = empty(self.request, 'paginate_by', 10)
        self.o = empty(self.request, 'o', "-created_at")
        self.f = empty(self.request, 'f', 'client__cedule') 
        self.q = empty(self.request, 'q', '')
        column_contains = u'%s__%s' % (self.f, 'contains')
        query = {column_contains: self.q}
        qs = self.model.objects.filter(**query).order_by(self.o)
        return qs.select_related('client')

    def get_context_data(self, **kwargs):
        context = super(ReciptList, self).get_context_data(**kwargs)
        context['opts'] = self.model._meta
        context['title'] = "Seleccione Registro para modificar"
        context['o'] = self.o
        context['f'] = self.f
        context['q'] = self.q
        context['paginate_by'] = self.paginate_by
        return context

 
class ReceiptDetail(LoginRequiredMixin, DetailView):
    model = Receipt
    template_name = 'receipt/detail.html'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super(ReceiptDetail, self).get_context_data(**kwargs)
        context['opts'] = self.model._meta
        context['title'] = self.object
        return context


class ReceiptCreateView(LoginRequiredMixin, TemplateView):
    template_name = 'receipt/create_form.html'

    def get_context_data(self, **kwargs):
        context = super(ReceiptCreateView, self).get_context_data(**kwargs)
        qs_services = Service.objects.filter(is_public=True)
        context['title'] = "Nuevo comprobante"
        context['services'] = qs_services
        return context


class ReceiptSaveView(LoginRequiredMixin, View):
    success_url = reverse_lazy('registry:receipt_list' )

    def post(self, request, *args, **kwargs):
        cedule = request.POST.get('cedule')
        qs = Person.objects.filter(cedule=cedule)
        person = Person()
        if qs.exists():
            person = qs[0]
        person.cedule = cedule
        person.first_name = request.POST.get('first_name')
        person.last_name = request.POST.get('last_name')
        person.email = request.POST.get('email')
        person.cellphone = request.POST.get('cellphone')
        person.address = request.POST.get('address')
        person.save()
        
        receipt = Receipt()
        receipt.number = Receipt.objects.count() + 1
        receipt.client = person
        receipt.date = request.POST.get('date')
        receipt.total = request.POST.get('total')
        receipt.created_by = request.user.username
        receipt.save()
        
        services = json.loads(request.POST.get('servs2'))
        qs = Service.objects.filter(id__in=services)
        details = [Detail(receipt=receipt, service=d, cost=d.cost) for d in qs]
        services_extra = Service.objects.filter(is_public=False)
        for d in services_extra:
            details.append(Detail(receipt=receipt, service=d, cost=d.cost))
        Detail.objects.bulk_create(details)
        receipt.total = sum([d.cost for d in details])
        receipt.save()

        messages.success(self.request, "Comprobante creado correctamente")
        success_url = reverse('registry:receipt_detail', kwargs={'pk': receipt.pk})
        return HttpResponseRedirect(success_url)


class ReceiptDeleteView(View):
    success_url = reverse_lazy('registry:receipt_list' )

    def get(self, request, pk, *args, **kwargs):
        Receipt.objects.get(id=pk).delete()
        messages.success(request, "Comprobante eliminado correctamente")
        return HttpResponseRedirect(self.success_url)

apps/registry/views/service.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.views import View
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse, reverse_lazy
from django.utils.text import capfirst
from django.utils.encoding import force_bytes, force_text

from apps.utils.util import empty

from ..models.service import Service
from ..forms.service import ServiceModelForm


class ServiceList(LoginRequiredMixin, ListView):
    model = Service
    template_name = 'service/list.html'

    def get_paginate_by(self, queryset):
        if 'all' in self.request.GET:
            return None
        return ListView.get_paginate_by(self, queryset)

    def get_queryset(self):
        self.paginate_by = empty(self.request, 'paginate_by', 10)
        self.o = empty(self.request, 'o', 'code')
        self.f = empty(self.request, 'f', 'description')
        self.q = empty(self.request, 'q', '')
        column_contains = u'%s__%s' % (self.f, 'contains')
        query = {column_contains: self.q}
        return self.model.objects.filter(**query).order_by(self.o)

    def get_context_data(self, **kwargs):
        context = super(ServiceList, self).get_context_data(**kwargs)
        context['opts'] = self.model._meta
        context['title'] = "Seleccione servicio para modificar"
        context['o'] = self.o
        context['f'] = self.f
        context['q'] = self.q
        context['paginate_by'] = self.paginate_by
        return context


class ServiceCreateView(LoginRequiredMixin, CreateView):
    model = Service
    form_class = ServiceModelForm
    template_name = 'service/form.html'
    success_url = reverse_lazy('registry:service_list')

    def get_context_data(self, **kwargs):
        context = super(ServiceCreateView, self).get_context_data(**kwargs)
        context['opts'] = self.model._meta
        context['title'] = "Registrar nuevo Servicio"
        return context

    def form_valid(self, form):
        self.object = form.save(commit=True)
        msg = (' %(name)s "%(obj)s" fue creado satisfactoriamente.') % {
            'name': capfirst(force_text(self.model._meta.verbose_name)),
            'obj': force_text(self.object)
        }
        if self.object.id:
            messages.success(self.request, msg)
        return super(ServiceCreateView, self).form_valid(form)


class ServiceUpdateView(LoginRequiredMixin, UpdateView):
    model = Service
    form_class = ServiceModelForm
    template_name = 'service/form.html'
    success_url = reverse_lazy('registry:service_list')

    def get_context_data(self, **kwargs):
        context = super(ServiceUpdateView, self).get_context_data(**kwargs)
        context['opts'] = self.model._meta
        context['title'] = 'Actualizar servicio'
        return context

    def form_valid(self, form):
        self.object = form.save(commit=True)
        msg = '%(name)s "%(obj)s" fue cambiado satisfactoriamente.' % {
            'name': capfirst(force_text(self.model._meta.verbose_name)),
            'obj': force_text(self.object)
        }
        messages.success(self.request, msg)
        return super(ServiceUpdateView, self).form_valid(form)
    

class ServiceDeleteView(View):
    success_url = reverse_lazy('registry:service_list' )

    def get(self, request, pk, *args, **kwargs):
        Service.objects.get(id=pk).delete()
        messages.success(request, "Servicio eliminado correctamente")
        return HttpResponseRedirect(self.success_url)


# class ServiceDeleteView(LoginRequiredMixin, DeleteView):
#     model = Service
#     success_url = reverse_lazy('registry:service_list' )
#     template_name = 'service/confirm_delete.html'

#     def get_context_data(self, **kwargs):
#         context = super(ServiceDeleteView, self).get_context_data(**kwargs)
#         context['opts'] = self.model._meta
#         context['title'] = ('Eliminar categoría %s') % self.object
#         return context

#     def delete(self, request, *args, **kwargs):
#         try:
#             d = self.get_object()
#             d.delete()
#             msg = (' %(name)s "%(obj)s" fue eliminado satisfactorialmente.') % {
#                 'name': capfirst(force_text(self.model._meta.verbose_name)),
#                 'obj': force_text(d)
#             }
#             if not d.id:
#                 messages.success(self.request, msg)
#         except Exception as e:
#             messages.error(request, e)
#         return HttpResponseRedirect(self.success_url)

apps/registry/templates/receipt/create_form.html
{% extends 'base.html' %}
<!-- breadcrumbs -->
{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'registry:receipt_list' %}">Registros</a></li>
<li class="breadcrumb-item">{{title}}</li>
{% endblock breadcrumb %}
<!-- main content -->
{% block content %}
<h1>Registro | <small class="text-muted">{{title}}</small></h1>
<style>
    .error {
        color: red;
        font-size: .85em;
    }
</style>

<form name='myForm' method="POST" action="{% url 'registry:receipt_save' %}">
    {% csrf_token %}
    <div class="form-row">
        <div class="form-group col-md-3">
            <label for="cedule">DNI/RUC*</label>
            <input type="text" placeholder="Ingrese DNI/RUC" class="form-control" id="cedule" name="cedule" autocomplete="off">
        </div>
        <div class="form-group col-md-9">
            <label for="first_name">Nombres o Razon Social*</label>
            <input type="text" placeholder="Ingrese Nombres o Razon Social" class="form-control" id="first_name" name="first_name">
        </div>
    </div>
    <div class="form-group">
        <label for="last_name">Apellidos</label>
        <input type="text" placeholder="Ingrese Apellidos" class="form-control" id="last_name" name="last_name">
    </div>
    <div class="form-row">
        <div class="form-group col-md-9">
            <label for="email">Correo</label>
            <input type="email" placeholder="Ingrese correo" class="form-control" id="email" name="email">
        </div>
        <div class="form-group col-md-3">
            <label for="cellphone">Celular</label>
            <input type="text" placeholder="Ingrese celular" class="form-control" id="cellphone" name="cellphone">
        </div>
    </div>
    <div class="form-group">
        <label for="address">Dirección*</label>
        <input type="text" placeholder="Ingrese dirección" class="form-control" id="address" name="address">
    </div>

    <div class="form-row">
        <div class="form-group col-md-3">
            <label for="date">Fecha*</label>
            <input type="date" class="form-control" id="date" name="date">
        </div>
        <div class="form-group col-md-3">
            <label for="total">Total*</label>
            <input type="number" step="any" class="form-control" id="total" value="0" name="total" readonly>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th scope="col" style="width: 1em;"></th>
                <th scope="col">Servicios</th>
                <th scope="col">Costo</th>
            </tr>
        </thead>
        <tbody>
            {% for d in services %}
            <tr>
                <th scope="row">
                    <div class="form-check">
                        <input class="form-check-input serv" type="checkbox" data-id='{{d.id}}' data-cost='{{d.cost}}'>
                    </div>
                </th>
                <td>{{d.code}} {{d.description}}</td>
                <td>{{d.cost}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <input type="hidden" name="servs2" id="servs2">
    <button type="submit" class="btn btn-primary"><i class="fa fa-send" aria-hidden="true"></i> Registrar</button>
</form>


<script>
    let total = 0;
    let ids = [];
    $(".serv").change(function() {
        const id = $(this).data('id');
        let checked = $(this).is(':checked')
        const costo = parseFloat($(this).data('cost'));
        if (checked) {
            total += costo
            ids.push(id);
        } else {
            total -= costo
            const idx = ids.indexOf(id);
            ids.splice(idx, 1)
        }
        $("input#servs2").val(JSON.stringify(ids))
        $("input#total").val(total.toFixed(2))
    })

    $("form[name='myForm']").validate({
        rules: {
            cedule: "required",
            first_name: "required",
            // email: {
            //     required: true,
            //     email: true
            // },
            // cellphone: "required",
            address: "required",
            date: "required",
            total: "required",
        },
        // Specify validation error messages
        messages: {
            cedule: "Por favor ingrese DNI/RUC",
            first_name: "Por favor ingrese Nombres o Razón social",
            // email: "Please enter a valid email address",
            // cellphone: "Please enter your cellphone",
            date: "Ingrese una fecha por favor",
            total: "Ingrese el total",
        },
        // Make sure the form is submitted to the destination defined
        // in the "action" attribute of the form when valid
        submitHandler: function(form) {
            if (ids.length) {
                form.submit();
            } else {
                alert("Debes seleccionar al menos un servicio")
            }
        }
    });

    $("input#cedule").keyup(function() {
        const cedule = $(this).val();
        if (cedule.length > 7 && cedule.length < 12) {
            const myForm = $("form[name='myForm']")
            const params = {
                cedule
            }
            $.get("{% url 'registry:person_search' %}", params,
                function(response, textStatus, jqXHR) {
                    myForm.find('input#first_name').val('');
                    myForm.find('input#last_name').val('');
                    myForm.find('input#email').val('');
                    myForm.find('input#cellphone').val('');
                    myForm.find('input#address').val('');
                    if (response.ok) {
                        myForm.find('input#first_name').val(response.person.first_name);
                        myForm.find('input#last_name').val(response.person.last_name);
                        myForm.find('input#email').val(response.person.email);
                        myForm.find('input#cellphone').val(response.person.cellphone);
                        myForm.find('input#address').val(response.person.address);
                    }
                },
            );
        }
    })
</script>
{% endblock content %}

apps/registry/templates/receipt/detail.html
{% extends 'base.html' %}
<!-- breadcrumbs -->
{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'registry:receipt_list' %}">Registros</a></li>
<li class="breadcrumb-item">{{title}}</li>
{% endblock breadcrumb %}
<!-- main content -->
{% block content %}
<h1>{{opts.verbose_name}} | <small class="text-muted">Nro: {{title}}</small></h1>

<div class="row">
    <div class="col-md-9">
        <small>DNI/RUC:</small>
        <p>{{object.client.cedule}}</p>
        <small>Contribuyente:</small>
        <p>
            {% if object.client.last_name %}
            <strong>{{object.client.last_name|upper}}</strong> {% endif %} {{object.client.first_name}}
        </p>
    </div>
    <div class="col-md-3">
        <small>Fecha:</small>
        <p>{{object.date | date:'d/m/Y'}}</p>
        <small>Total:</small>
        <p><strong>S/. {{object.total}}</strong></p>
    </div>
</div>

<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th scope="col" style="width: 1em;">#</th>
                <th scope="col">Servicios</th>
                <th scope="col">Costo</th>
            </tr>
        </thead>
        <tbody>
            {% for d in object.details.all %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{d.service.code}} {{d.service.description}}</td>
                <td>{{d.cost}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<!-- Button trigger modal -->
<button type="button" class="btn btn-danger btn-sm js-confirm" data-action="{% url 'registry:receipt_delete' object.pk %}" data-message="Estás seguro de eliminar este registro?. Toda información relacionada a este será eliminada">
    <i class="fa fa-ban" aria-hidden="true"></i> Eliminar comprobante
</button>

<a class="btn btn-outline-info" href="{% url 'registry:my_report' object.pk %}">Descargar pdf</a>

<!-- confirm-dialog -->
{% include 'partial/confirm-dialog.html' %}
<!-- endblock content -->
{% endblock content %}

apps/registry/templates/receipt/list.html
{% extends 'base.html' %}
<!-- breadcrumbs -->
{% block breadcrumb %}
<li class="breadcrumb-item">Registros</li>
{% endblock breadcrumb %}
<!-- main content -->
{% block content %}
<h1>Registros | <small class="text-muted">{{title}}</small></h1>

<div class="row">
    <div class="col-md-6 offset-md-3 mb-2">
        <form action="">
            <div class="input-group">
                <select class="custom-select" id="f" name="f">
                    <option value="client__first_name" {% if f == 'client__first_name' %} selected {% endif %}>Nombres</option>
                    <option value="client__last_name" {% if f == 'client__last_name' %} selected {% endif %}>Apellidos</option>
                    <option value="client__cedule" {% if f == 'client__cedule' %} selected {% endif %}>DNI</option>
                </select>
                <input type="text" name="q" class="form-control" value="{{q}}" placeholder="Search for..." style="width: 50%;">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit">Filtrar</button>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-3 mb-2">
        <a class="btn btn-primary float-right" href="{% url 'registry:receipt_create' %}" rel="tooltip" title="Nuevo registro">
            <i class="fa fa-plus" aria-hidden="true"></i> Nuevo
        </a>
    </div>
</div>
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th><small>Registro</small></th>
                <th>Cliente</th>
                <th><small>DNI Cliente</small></th>
                <th>Fecha</th>
                <th><small>Opción</small></th>
                <!-- <th>Fecha Vencimiento</th> -->
            </tr>
        </thead>
        <tbody>
            {% for d in object_list %}
            <tr>
                <td scope="row">{% if is_paginated %} {{ page_obj.start_index|add:forloop.counter0 }} {% else %} {{ forloop.counter }} {% endif %}</td>
                <td>
                    <a href="{% url 'registry:receipt_detail' d.id %}" rel="tooltip" title="Ver detalles">
                        <strong>{{ d.number }}</strong>
                    </a>
                </td>
                <td>{{d.client.last_name | upper}}, {{d.client.first_name}}</td>
                <td>{{d.client.cedule}}</td>
                <td><small>{{d.date | date:'d/m/Y'}}</small></td>
                <td>
                    <div>
                        <a class="btn btn-sm btn-primary" href="{% url 'registry:receipt_detail' d.id %}" rel="tooltip" title="Ver detalles">
                            <span class="fa fa-eye"></span>
                        </a>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="panel">
    {% if is_paginated %} {% load paginator %} {% paginator %} {% else %}
    <div class="col-md-12">
        {{ object_list.count }} {% ifequal object_list.count 1 %}{{ opts.verbose_name|capfirst }}{% else %} {{ opts.verbose_name_plural|capfirst }}{% endifequal %}
    </div>
    {% endif %}
</div>
<hr> {% endblock content %}