apps/account/urls.py
from django.urls import include, path
from rest_framework import routers
from .views.user import UserProfileView, UserListView, change_password  # , UserDetailView

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
app_name = 'account'
urlpatterns = [
    path('usuarios', UserListView.as_view(), name="user_list"),
    # path('usuarios/<int:pk>', UserDetailView.as_view(), name="user_detail"),
    path('profile', UserProfileView.as_view(), name="user_profile"),
    path('change-password/', change_password, name='change_password'),
]

apps/dauth/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views                                        #from django.views.generic import TemplateView              # Wire up our API using automatic URL routing.             # Additionally, we include login URLs for the browsable API
app_name = 'dauth'
urlpatterns = [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),

]

apps/registry/urls.py
from django.urls import include, path
from rest_framework import routers
from apps.registry.export.receipt import MyReceiptView
from apps.registry.views.person import PersonSearchView

from apps.registry.views.receipt import ReceiptCreateView, ReceiptDeleteView, ReceiptDetail, ReceiptSaveView, ReciptList
from apps.registry.views.service import ServiceCreateView, ServiceDeleteView, ServiceList, ServiceUpdateView

app_name = 'registry'
urlpatterns = [
    path('receipt/list', ReciptList.as_view(), name="receipt_list"),
    path('receipt/create', ReceiptCreateView.as_view(), name="receipt_create"),
    path('receipt/save', ReceiptSaveView.as_view(), name="receipt_save"),
    path('receipt/<uuid:pk>/detail', ReceiptDetail.as_view(), name="receipt_detail"),
    path('person/search', PersonSearchView.as_view(), name="person_search"),
    path('receipt/<uuid:pk>/delete', ReceiptDeleteView.as_view(), name="receipt_delete"),
    
    path('service/list', ServiceList.as_view(), name='service_list'),
    path('service/crear', ServiceCreateView.as_view(), name='service_create'),
    path('service/<uuid:pk>/update', ServiceUpdateView.as_view(), name='service_update'),
    path('service/<uuid:pk>/delete', ServiceDeleteView.as_view(), name='service_delete'),
    
    path('export/receipt/<uuid:pk>', MyReceiptView.as_view(), name='my_report'),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import TemplateView
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from apps.registry.views.dashboard import DashboardView

urlpatterns = [
    path('', TemplateView.as_view(template_name="index.html"), name='index'),
    path('admin/', admin.site.urls),
    # path('summernote/', include('django_summernote.urls')),
    path('dauth/', include('apps.dauth.urls'), name='dauth'),
    
    path('dashboard', DashboardView.as_view(), name='dashboard'),
    path('account/', include('apps.account.urls'), name='account'),
    path('registry/', include('apps.registry.urls'), name='registry'),
    
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partial/confirm-dialog.html
<!-- Modal -->
<div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog modal-sm modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Diálogo de confirmación</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Estás seguro?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fa fa-ban" aria-hidden="true"></i> Cancelar</button>
                <a href="" class="btn btn-danger">
                    <i class="fa fa-check" aria-hidden="true"></i> Confirmar
                </a>
            </div>
        </div>
    </div>
</div>

<script>
    $(".js-confirm").on('click', event => {
        const target = $(event.target);
        const modal = $("#confirmModal");
        modal.find('.modal-body').find('p').text(target.data('message'))
        modal.find('.modal-footer').find('a').attr('href', target.data('action'))
        modal.modal('show');
    });
</script>

templates/partial/footer.html
<footer class="footer text-white bg-primary">
    <div class="container py-3 text-center">
        <p>&copy; Copyright DevSolutions. Todos los derechos reservados.
        </p>
        <p>Diseñado y desarrollado por
            <a target="_blank" href="https://www.facebook.com/DevSolutions.pe" style="color: gold">Aldo AC</a>
        </p>
    </div>
</footer>

templates/partial/header.html
{% load static %}
<nav id="navbarMain" class="navbar navbar-expand-lg navbar-dark fixed-top shadow bg-primary">
    <a class="navbar-brand" href="/">
        <img src="{#% static 'img/logo1.png' %#}" height="40" alt="NO LOGO">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fa fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'registry:receipt_list' %}">
                    <i class="fa fa-bookmark" aria-hidden="true"></i> Registros
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'registry:service_list' %}">
                    <i class="fa fa-list" aria-hidden="true"></i> Services
                </a>
            </li>
        </ul>
        <ul class="navbar-nav mr-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-user-circle" aria-hidden="true"></i> {{user|capfirst}}
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                    {% comment %}
                    <a class="dropdown-item" href="{% url 'account:user_profile' %}">
                        <i class="fa fa-user"></i> Perfil
                    </a>
                    <a class="dropdown-item" href="{% url 'account:change_password' %}">
                        <i class="fa fa-lock"></i> Cambiar contraseña
                    </a>
                    {% endcomment %}
                    <a class="dropdown-item" href="{% url 'dauth:logout' %}">
                        <i class="fa fa-sign-out"></i> Cerrar sesión
                    </a>
                </div>
            </li>
        </ul>
    </div>
</nav>
<script>
    $(function() {
        $(".navbar-nav .nav-item a").each(function() {
            const $a = $(this);
            const href = $a.attr('href');
            const path = location.pathname;
            if (href == path) {
                $a.parent().addClass('active');
            }
        });
    });
</script>